"""proveedores

Revision ID: 83f878139754
Revises: c07f1cbffa72
Create Date: 2026-10-01 14:27:15.141128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f878139754'
down_revision: Union[str, Sequence[str], None] = 'c07f1cbffa72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('tax_id', sa.String(length=20), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('commercial_names', sa.JSON(), nullable=False),
    sa.Column('match_names', sa.JSON(), nullable=False),
    sa.Column('payment_emails', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['pagos_proveedores.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['pagos_proveedores.actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['pagos_proveedores.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pagos_proveedores'
    )
    op.create_index('ix_providers_company_active_name', 'providers', ['company_id', 'is_active', 'legal_name'], unique=False, schema='pagos_proveedores')
    op.create_index('uq_providers_company_tax_id_active', 'providers', ['company_id', 'tax_id'], unique=True, schema='pagos_proveedores', postgresql_where=sa.text('is_active'), mssql_where=sa.text('is_active = 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )