"""lotes

Revision ID: d70bd8fa94a8
Revises: 83f878139754
Create Date: 2026-10-01 14:49:12.650567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70bd8fa94a8'
down_revision: Union[str, Sequence[str], None] = '83f878139754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('template_code', sa.String(length=100), nullable=True),
    sa.Column('custom_subject', sa.String(length=998), nullable=True),
    sa.Column('custom_message', sa.Text(), nullable=True),
    sa.Column('notification_dispatch_id', sa.String(length=36), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'sending', 'sent')", name='ck_batches_status'),
    sa.ForeignKeyConstraint(['created_by'], ['pagos_proveedores.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['pagos_proveedores.actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['pagos_proveedores.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pagos_proveedores'
    )
    op.create_index('ix_batches_company_created', 'batches', ['company_id', 'created_at'], unique=False, schema='pagos_proveedores')
    op.create_table('batch_deliveries',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('tax_id', sa.String(length=20), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('payment_emails', sa.JSON(), nullable=False),
    sa.Column('totals', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['pagos_proveedores.batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['pagos_proveedores.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['pagos_proveedores.actors.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['pagos_proveedores.providers.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['pagos_proveedores.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'sequence', name='uq_batch_deliveries_batch_sequence'),
    schema='pagos_proveedores'
    )
    op.create_table('batch_files',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('parse_status', sa.String(length=10), nullable=False),
    sa.Column('parse_error', sa.String(length=500), nullable=True),
    sa.Column('used_ocr', sa.Boolean(), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=255), nullable=True),
    sa.Column('beneficiary_tax_id', sa.String(length=30), nullable=True),
    sa.Column('account', sa.String(length=60), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=2), nullable=True),
    sa.Column('operation_date', sa.Date(), nullable=True),
    sa.Column('extracted', sa.JSON(), nullable=True),
    sa.Column('already_sent_in_batch_id', sa.String(length=36), nullable=True),
    sa.Column('delivery_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("parse_status IN ('parsed', 'error')", name='ck_batch_files_parse_status'),
    sa.ForeignKeyConstraint(['already_sent_in_batch_id'], ['pagos_proveedores.batches.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['pagos_proveedores.batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['pagos_proveedores.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['pagos_proveedores.actors.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['pagos_proveedores.batch_deliveries.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['pagos_proveedores.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'sequence', name='uq_batch_files_batch_sequence'),
    schema='pagos_proveedores'
    )
    op.create_index('ix_batch_files_company_sha256', 'batch_files', ['company_id', 'sha256'], unique=False, schema='pagos_proveedores')
    op.create_index('uq_batch_files_batch_sha256_active', 'batch_files', ['batch_id', 'sha256'], unique=True, schema='pagos_proveedores', postgresql_where=sa.text('is_active'), mssql_where=sa.text('is_active = 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )