"""update  auth

Revision ID: 05514603cf38
Revises: f90d2c4ddbeb
Create Date: 2026-09-27 10:08:50.583644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05514603cf38'
down_revision: Union[str, Sequence[str], None] = 'f90d2c4ddbeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_normalized_email_key'), 'users', schema='auth', type_='unique')
    op.drop_column('users', 'normalized_email', schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )