"""perfil, documentos de identidad y api keys

Revision ID: 28950766fbb9
Revises: 37ba63fd1552
Create Date: 2026-09-27 16:21:59.555154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28950766fbb9'
down_revision: Union[str, Sequence[str], None] = '37ba63fd1552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='auth'
    )
    op.create_table('identity_document_types',
    sa.Column('issuing_country_code', sa.String(length=2), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("category IN ('national_identity', 'residence', 'passport', 'other')"),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['issuing_country_code'], ['auth.countries.code'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuing_country_code', 'code'),
    schema='auth'
    )
    op.create_table('api_keys',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('membership_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['auth.companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['membership_id', 'company_id'], ['auth.memberships.id', 'auth.memberships.company_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_api_keys_user_id'), 'api_keys', ['user_id'], unique=False, schema='auth')
    op.create_table('user_identity_documents',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('document_type_id', sa.String(length=36), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('normalized_number', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['auth.identity_document_types.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_type_id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_user_identity_documents_user_id'), 'user_identity_documents', ['user_id'], unique=False, schema='auth')
    op.add_column('user_profiles', sa.Column('birth_date', sa.Date(), nullable=True), schema='auth')
    op.add_column('user_profiles', sa.Column('nationality_country_code', sa.String(length=2), nullable=True), schema='auth')
    op.create_foreign_key(None, 'user_profiles', 'countries', ['nationality_country_code'], ['code'], source_schema='auth', referent_schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )