"""elimina csrf_hash de sessions

Revision ID: 81b88abef3a5
Revises: 4188b68e5210
Create Date: 2026-09-27 13:54:59.151945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b88abef3a5'
down_revision: Union[str, Sequence[str], None] = '4188b68e5210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # Decisión del usuario: Bearer + refresh en body, sin cookies, por lo que no
    # hay CSRF. La tabla estaba vacía al crear esta revisión.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'csrf_hash', schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )