"""estructura inicial audit

Revision ID: 38dd37f41c1e
Revises: 
Create Date: 2026-09-27 18:12:15.806976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38dd37f41c1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # El schema audit lo crea platform_audit.migrate antes de migrar.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('parent_operation_id', sa.String(length=36), nullable=True),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('service_version', sa.String(length=30), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('success', 'warning', 'error')"),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_index('ix_audit_logs_service_started_at', 'logs', ['service', 'started_at'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_logs_trace_id'), 'logs', ['trace_id'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_logs_user_id'), 'logs', ['user_id'], unique=False, schema='audit')
    op.create_table('logs_detail',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("level IN ('info', 'success', 'warning', 'error')"),
    sa.ForeignKeyConstraint(['log_id'], ['audit.logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_logs_detail_log_id'), 'logs_detail', ['log_id'], unique=False, schema='audit')
    op.create_table('logs_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phase', sa.String(length=10), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("phase IN ('start', 'end', 'error')"),
    sa.ForeignKeyConstraint(['log_id'], ['audit.logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_logs_steps_log_id'), 'logs_steps', ['log_id'], unique=False, schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )