"""actores

Revision ID: 605d4653b27d
Revises: 
Create Date: 2026-09-28 00:35:42.255715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605d4653b27d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # El schema libro_mayor lo crea migrations/env.py antes de migrar.
    # actors se referencia a sí misma: cada actor se atribuye su propia alta.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('subject_ref', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("kind IN ('user', 'system', 'service')", name='ck_actors_kind'),
    sa.ForeignKeyConstraint(['created_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['libro_mayor.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'subject_ref'),
    schema='libro_mayor'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )