"""categorias por nombre

Revision ID: 7096d47b8a5d
Revises: 0708533d3e77
Create Date: 2026-09-30 10:58:48.524369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7096d47b8a5d'
down_revision: Union[str, Sequence[str], None] = '0708533d3e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # Decisión del usuario (2026-09-30): las categorías se identifican por nombre,
    # como en proyecto-05 (codigo/subcodigo); se retira el código generado.
    # Si ya hubiera dos categorías activas con el mismo nombre en el mismo nivel,
    # la creación del índice falla y la migración no se aplica (transaccional):
    # dar de baja o renombrar una de ellas y repetir.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_expense_categories_company_code_active'), table_name='expense_categories', schema='libro_mayor', postgresql_where='is_active')
    op.create_index('uq_expense_categories_sub_name_active', 'expense_categories', ['parent_id', 'name'], unique=True, schema='libro_mayor', postgresql_where=sa.text('parent_id IS NOT NULL AND is_active'), mssql_where=sa.text('parent_id IS NOT NULL AND is_active = 1'))
    op.create_index('uq_expense_categories_top_name_active', 'expense_categories', ['company_id', 'name'], unique=True, schema='libro_mayor', postgresql_where=sa.text('parent_id IS NULL AND is_active'), mssql_where=sa.text('parent_id IS NULL AND is_active = 1'))
    op.drop_column('expense_categories', 'code', schema='libro_mayor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )