"""companias sap y cuentas

Revision ID: 8b83c4465b06
Revises: 605d4653b27d
Create Date: 2026-09-28 00:41:41.941348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b83c4465b06'
down_revision: Union[str, Sequence[str], None] = '605d4653b27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # Índices únicos filtrados por is_active: una baja lógica no impide volver
    # a registrar la misma cuenta o compañía SAP.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('match_mode', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("match_mode IN ('exact', 'prefix')", name='ck_accounts_match_mode'),
    sa.ForeignKeyConstraint(['created_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['libro_mayor.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='libro_mayor'
    )
    op.create_index('uq_accounts_company_code_active', 'accounts', ['company_id', 'code'], unique=True, schema='libro_mayor', postgresql_where=sa.text('is_active'), mssql_where=sa.text('is_active = 1'))
    op.create_table('sap_companies',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('sap_schema', sa.String(length=128), nullable=False),
    sa.Column('source_view', sa.String(length=128), nullable=False),
    sa.Column('sync_start_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['libro_mayor.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='libro_mayor'
    )
    op.create_index('uq_sap_companies_company_active', 'sap_companies', ['company_id'], unique=True, schema='libro_mayor', postgresql_where=sa.text('is_active'), mssql_where=sa.text('is_active = 1'))
    op.create_index('uq_sap_companies_schema_active', 'sap_companies', ['sap_schema'], unique=True, schema='libro_mayor', postgresql_where=sa.text('is_active'), mssql_where=sa.text('is_active = 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )