"""homologacion de centros de costo

Revision ID: 9d1c3497b704
Revises: 7096d47b8a5d
Create Date: 2026-09-30 15:33:39.072613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1c3497b704'
down_revision: Union[str, Sequence[str], None] = '7096d47b8a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # Homologación centro de costo → área de auth (acuerdo): decide la visibilidad
    # de ledger.view con alcance area. Un centro, una sola área (índice único activo).
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_center_mappings',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('cost_center_code', sa.String(length=100), nullable=False),
    sa.Column('match_mode', sa.String(length=10), nullable=False),
    sa.Column('auth_area_id', sa.String(length=36), nullable=False),
    sa.Column('area_code', sa.String(length=50), nullable=False),
    sa.Column('area_name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("match_mode IN ('exact', 'prefix')", name='ck_cost_center_mappings_match_mode'),
    sa.ForeignKeyConstraint(['created_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['libro_mayor.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='libro_mayor'
    )
    op.create_index('ix_cost_center_mappings_company_area', 'cost_center_mappings', ['company_id', 'auth_area_id'], unique=False, schema='libro_mayor')
    op.create_index('uq_cost_center_mappings_company_code_active', 'cost_center_mappings', ['company_id', 'cost_center_code'], unique=True, schema='libro_mayor', postgresql_where=sa.text('is_active'), mssql_where=sa.text('is_active = 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )