"""sincronizaciones y lineas

Revision ID: a5f6bc046f7c
Revises: d96307b64e1a
Create Date: 2026-09-28 01:09:47.405757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f6bc046f7c'
down_revision: Union[str, Sequence[str], None] = 'd96307b64e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # uq_sync_runs_account_open: una sola ejecución pendiente o en curso por cuenta.
    # ledger_lines: una fila por línea SAP (company_id, transaccion_id, linea).
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('days_total', sa.Integer(), nullable=False),
    sa.Column('days_done', sa.Integer(), nullable=False),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('safe_error', sa.String(length=500), nullable=True),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("kind IN ('sync')", name='ck_sync_runs_kind'),
    sa.CheckConstraint("origin IN ('manual', 'schedule')", name='ck_sync_runs_origin'),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name='ck_sync_runs_status'),
    sa.CheckConstraint('date_to >= date_from', name='ck_sync_runs_range'),
    sa.ForeignKeyConstraint(['account_id'], ['libro_mayor.accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['libro_mayor.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='libro_mayor'
    )
    op.create_index('ix_sync_runs_company_created', 'sync_runs', ['company_id', 'created_at'], unique=False, schema='libro_mayor')
    op.create_index('ix_sync_runs_status_created', 'sync_runs', ['status', 'created_at'], unique=False, schema='libro_mayor')
    op.create_index('uq_sync_runs_account_open', 'sync_runs', ['account_id'], unique=True, schema='libro_mayor', postgresql_where=sa.text("status IN ('pending', 'running')"), mssql_where=sa.text("status IN ('pending', 'running')"))
    op.create_table('ledger_lines',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('last_sync_run_id', sa.String(length=36), nullable=False),
    sa.Column('sap_transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('sap_line', sa.Integer(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('folio', sa.String(length=50), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=150), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('line_comment', sa.String(length=255), nullable=True),
    sa.Column('counter_account_code', sa.String(length=100), nullable=True),
    sa.Column('counter_account_name', sa.String(length=150), nullable=True),
    sa.Column('reference_1', sa.String(length=200), nullable=True),
    sa.Column('reference_2', sa.String(length=200), nullable=True),
    sa.Column('reference_3', sa.String(length=200), nullable=True),
    sa.Column('amount_local', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('amount_foreign', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('cost_center_code', sa.String(length=100), nullable=True),
    sa.Column('cost_center_area', sa.String(length=100), nullable=True),
    sa.Column('cost_center_name', sa.String(length=100), nullable=True),
    sa.Column('sap_created_at', sa.DateTime(), nullable=True),
    sa.Column('sap_updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['libro_mayor.accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['last_sync_run_id'], ['libro_mayor.sync_runs.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['libro_mayor.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'sap_transaction_id', 'sap_line', name='uq_ledger_lines_sap_key'),
    schema='libro_mayor'
    )
    op.create_index('ix_ledger_lines_account_posting', 'ledger_lines', ['account_id', 'posting_date'], unique=False, schema='libro_mayor')
    op.create_index('ix_ledger_lines_company_cost_center', 'ledger_lines', ['company_id', 'cost_center_code'], unique=False, schema='libro_mayor')
    op.create_index('ix_ledger_lines_company_posting', 'ledger_lines', ['company_id', 'posting_date'], unique=False, schema='libro_mayor')
    op.create_index('ix_ledger_lines_company_sap_updated', 'ledger_lines', ['company_id', 'sap_updated_at'], unique=False, schema='libro_mayor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )