"""horario y delta

Revision ID: d608ca9bd49a
Revises: a5f6bc046f7c
Create Date: 2026-09-28 01:20:21.626151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd608ca9bd49a'
down_revision: Union[str, Sequence[str], None] = 'a5f6bc046f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_runs', sa.Column('schedule_slot', sa.DateTime(timezone=True), nullable=True), schema='libro_mayor')
    op.create_index('uq_sync_runs_account_slot', 'sync_runs', ['account_id', 'schedule_slot'], unique=True, schema='libro_mayor', postgresql_where=sa.text('schedule_slot IS NOT NULL'), mssql_where=sa.text('schedule_slot IS NOT NULL'))
    # ### end Alembic commands ###

    # Escrito a mano: autogenerate no detecta cambios en CHECK. Se reemplaza la
    # restricción para admitir los tipos del horario (initial, delta). Las filas
    # existentes (kind='sync') la cumplen.
    op.drop_constraint('ck_sync_runs_kind', 'sync_runs', schema='libro_mayor', type_='check')
    op.create_check_constraint(
        'ck_sync_runs_kind', 'sync_runs', "kind IN ('sync', 'initial', 'delta')", schema='libro_mayor'
    )


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )