"""categorias reglas y consultas en vivo

Revision ID: f1cfc1eac2ab
Revises: d608ca9bd49a
Create Date: 2026-09-30 06:12:59.022829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cfc1eac2ab'
down_revision: Union[str, Sequence[str], None] = 'd608ca9bd49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # Categorías y reglas, reclasificaciones, consultas en vivo (por días) y la
    # clasificación de ledger_lines (rule_id NULL = sin clasificar).
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['libro_mayor.expense_categories.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['libro_mayor.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='libro_mayor'
    )
    op.create_index('uq_expense_categories_company_code_active', 'expense_categories', ['company_id', 'code'], unique=True, schema='libro_mayor', postgresql_where=sa.text('is_active'), mssql_where=sa.text('is_active = 1'))
    op.create_table('live_queries',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('accounts', sa.JSON(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parts_total', sa.Integer(), nullable=False),
    sa.Column('parts_done', sa.Integer(), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('safe_error', sa.String(length=500), nullable=True),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name='ck_live_queries_status'),
    sa.CheckConstraint('date_to >= date_from', name='ck_live_queries_range'),
    sa.ForeignKeyConstraint(['created_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['libro_mayor.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='libro_mayor'
    )
    op.create_index('ix_live_queries_company_created', 'live_queries', ['company_id', 'created_at'], unique=False, schema='libro_mayor')
    op.create_index('uq_live_queries_user_open', 'live_queries', ['created_by'], unique=True, schema='libro_mayor', postgresql_where=sa.text("status IN ('pending', 'running')"), mssql_where=sa.text("status IN ('pending', 'running')"))
    op.create_table('expense_rules',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('counter_account_code', sa.String(length=100), nullable=True),
    sa.Column('cost_center_code', sa.String(length=100), nullable=True),
    sa.Column('include_text', sa.String(length=255), nullable=True),
    sa.Column('exclude_text', sa.String(length=255), nullable=True),
    sa.Column('amount_min', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('amount_max', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('report_name', sa.String(length=150), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint('amount_min IS NULL OR amount_max IS NULL OR amount_min <= amount_max', name='ck_expense_rules_amounts'),
    sa.ForeignKeyConstraint(['category_id'], ['libro_mayor.expense_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['libro_mayor.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='libro_mayor'
    )
    op.create_index('ix_expense_rules_company_priority', 'expense_rules', ['company_id', 'is_active', 'priority'], unique=False, schema='libro_mayor')
    op.create_table('live_query_parts',
    sa.Column('live_query_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('safe_error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name='ck_live_query_parts_status'),
    sa.ForeignKeyConstraint(['created_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['live_query_id'], ['libro_mayor.live_queries.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['libro_mayor.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('live_query_id', 'day', name='uq_live_query_parts_day'),
    schema='libro_mayor'
    )
    op.create_index('ix_live_query_parts_status_created', 'live_query_parts', ['status', 'created_at'], unique=False, schema='libro_mayor')
    op.create_table('classification_runs',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_checked', sa.Integer(), nullable=False),
    sa.Column('rows_changed', sa.Integer(), nullable=False),
    sa.Column('last_line_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('safe_error', sa.String(length=500), nullable=True),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("reason IN ('rule_change', 'manual')", name='ck_classification_runs_reason'),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name='ck_classification_runs_status'),
    sa.ForeignKeyConstraint(['created_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['libro_mayor.expense_rules.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['libro_mayor.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='libro_mayor'
    )
    op.create_index('ix_classification_runs_company_created', 'classification_runs', ['company_id', 'created_at'], unique=False, schema='libro_mayor')
    op.create_index('ix_classification_runs_status_created', 'classification_runs', ['status', 'created_at'], unique=False, schema='libro_mayor')
    op.create_table('live_query_lines',
    sa.Column('live_query_id', sa.String(length=36), nullable=False),
    sa.Column('part_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('sap_transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('sap_line', sa.Integer(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('folio', sa.String(length=50), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=150), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('line_comment', sa.String(length=255), nullable=True),
    sa.Column('counter_account_code', sa.String(length=100), nullable=True),
    sa.Column('counter_account_name', sa.String(length=150), nullable=True),
    sa.Column('reference_1', sa.String(length=200), nullable=True),
    sa.Column('reference_2', sa.String(length=200), nullable=True),
    sa.Column('reference_3', sa.String(length=200), nullable=True),
    sa.Column('amount_local', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('amount_foreign', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('cost_center_code', sa.String(length=100), nullable=True),
    sa.Column('cost_center_area', sa.String(length=100), nullable=True),
    sa.Column('cost_center_name', sa.String(length=100), nullable=True),
    sa.Column('sap_created_at', sa.DateTime(), nullable=True),
    sa.Column('sap_updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['libro_mayor.actors.id'], ),
    sa.ForeignKeyConstraint(['live_query_id'], ['libro_mayor.live_queries.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['libro_mayor.live_query_parts.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['libro_mayor.expense_rules.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['libro_mayor.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('live_query_id', 'sap_transaction_id', 'sap_line', name='uq_live_query_lines_sap_key'),
    schema='libro_mayor'
    )
    op.create_index('ix_live_query_lines_query_posting', 'live_query_lines', ['live_query_id', 'posting_date'], unique=False, schema='libro_mayor')
    op.add_column('ledger_lines', sa.Column('rule_id', sa.String(length=36), nullable=True), schema='libro_mayor')
    op.add_column('ledger_lines', sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True), schema='libro_mayor')
    op.create_index('ix_ledger_lines_company_rule', 'ledger_lines', ['company_id', 'rule_id'], unique=False, schema='libro_mayor')
    op.create_foreign_key('fk_ledger_lines_rule_id', 'ledger_lines', 'expense_rules', ['rule_id'], ['id'], source_schema='libro_mayor', referent_schema='libro_mayor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )