"""plantillas

Revision ID: 3915e16018ad
Revises: 57591c73d6e3
Create Date: 2026-10-01 11:59:19.804718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3915e16018ad'
down_revision: Union[str, Sequence[str], None] = '57591c73d6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('subject_template', sa.String(length=998), nullable=False),
    sa.Column('body_html_template', sa.Text(), nullable=True),
    sa.Column('body_text_template', sa.Text(), nullable=True),
    sa.Column('to_addresses', sa.JSON(), nullable=False),
    sa.Column('cc_addresses', sa.JSON(), nullable=False),
    sa.Column('bcc_addresses', sa.JSON(), nullable=False),
    sa.Column('reply_to', sa.String(length=320), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint('body_html_template IS NOT NULL OR body_text_template IS NOT NULL', name='ck_templates_body'),
    sa.ForeignKeyConstraint(['created_by'], ['notificaciones.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['notificaciones.actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['notificaciones.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='notificaciones'
    )
    op.create_index('uq_templates_company_code_active', 'templates', ['company_id', 'code'], unique=True, schema='notificaciones', postgresql_where=sa.text('is_active'), mssql_where=sa.text('is_active = 1'))
    op.add_column('messages', sa.Column('template_id', sa.String(length=36), nullable=True), schema='notificaciones')
    op.create_foreign_key(None, 'messages', 'templates', ['template_id'], ['id'], source_schema='notificaciones', referent_schema='notificaciones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )