"""historial de cambios

Revision ID: 55354ede02b0
Revises: 33ff2af681e9
Create Date: 2026-10-01 05:37:28.333601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55354ede02b0'
down_revision: Union[str, Sequence[str], None] = '33ff2af681e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_history',
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['notificaciones.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['notificaciones.actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['notificaciones.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='notificaciones'
    )
    op.create_index('ix_change_history_company_created', 'change_history', ['company_id', 'created_at'], unique=False, schema='notificaciones')
    op.create_index('ix_change_history_resource', 'change_history', ['resource_type', 'resource_id'], unique=False, schema='notificaciones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )