"""envios mensajes adjuntos e intentos

Revision ID: 57591c73d6e3
Revises: f8f8c64376a3
Create Date: 2026-10-01 08:31:36.508812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57591c73d6e3'
down_revision: Union[str, Sequence[str], None] = 'f8f8c64376a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatches',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('consumer', sa.String(length=50), nullable=True),
    sa.Column('consumer_reference', sa.String(length=100), nullable=True),
    sa.Column('requester_email', sa.String(length=320), nullable=True),
    sa.Column('notice_for_dispatch_id', sa.String(length=36), nullable=True),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("(kind = 'standard' AND notice_for_dispatch_id IS NULL) OR (kind = 'failure_notice' AND notice_for_dispatch_id IS NOT NULL)", name='ck_dispatches_notice_target'),
    sa.CheckConstraint("kind IN ('standard', 'failure_notice')", name='ck_dispatches_kind'),
    sa.ForeignKeyConstraint(['created_by'], ['notificaciones.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['notificaciones.actors.id'], ),
    sa.ForeignKeyConstraint(['notice_for_dispatch_id'], ['notificaciones.dispatches.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['notificaciones.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'created_by', 'idempotency_key', name='uq_dispatches_idempotency'),
    schema='notificaciones'
    )
    op.create_index('ix_dispatches_company_created', 'dispatches', ['company_id', 'created_at'], unique=False, schema='notificaciones')
    op.create_index('ix_dispatches_company_creator_created', 'dispatches', ['company_id', 'created_by', 'created_at'], unique=False, schema='notificaciones')
    op.create_table('messages',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('dispatch_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('consumer_reference', sa.String(length=100), nullable=True),
    sa.Column('to_addresses', sa.JSON(), nullable=False),
    sa.Column('cc_addresses', sa.JSON(), nullable=False),
    sa.Column('bcc_addresses', sa.JSON(), nullable=False),
    sa.Column('reply_to', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('message_id_header', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts_in_cycle', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notice_dispatch_id', sa.String(length=36), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("(status = 'cancelled' AND cancelled_at IS NOT NULL AND cancel_reason IS NOT NULL) OR (status <> 'cancelled' AND cancelled_at IS NULL AND cancel_reason IS NULL)", name='ck_messages_cancelled'),
    sa.CheckConstraint("cancel_reason IS NULL OR cancel_reason IN ('manual', 'expired')", name='ck_messages_cancel_reason'),
    sa.CheckConstraint("status IN ('pending', 'sending', 'retrying', 'sent', 'failed', 'uncertain', 'cancelled')", name='ck_messages_status'),
    sa.CheckConstraint('body_html IS NOT NULL OR body_text IS NOT NULL', name='ck_messages_body'),
    sa.CheckConstraint('sequence >= 1 AND attempts_in_cycle >= 0 AND size_bytes >= 0', name='ck_messages_counts'),
    sa.ForeignKeyConstraint(['created_by'], ['notificaciones.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['notificaciones.actors.id'], ),
    sa.ForeignKeyConstraint(['dispatch_id'], ['notificaciones.dispatches.id'], ),
    sa.ForeignKeyConstraint(['notice_dispatch_id'], ['notificaciones.dispatches.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['notificaciones.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispatch_id', 'sequence', name='uq_messages_dispatch_sequence'),
    schema='notificaciones'
    )
    op.create_index('ix_messages_dispatch_status', 'messages', ['dispatch_id', 'status'], unique=False, schema='notificaciones')
    op.create_index('ix_messages_status_last_attempt', 'messages', ['status', 'last_attempt_at'], unique=False, schema='notificaciones')
    op.create_index('ix_messages_status_locked_until', 'messages', ['status', 'locked_until'], unique=False, schema='notificaciones')
    op.create_index('ix_messages_status_next_attempt', 'messages', ['status', 'next_attempt_at'], unique=False, schema='notificaciones')
    op.create_table('message_attachments',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('content_purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint('(content IS NULL AND content_purged_at IS NOT NULL) OR (content IS NOT NULL AND content_purged_at IS NULL)', name='ck_message_attachments_purge'),
    sa.CheckConstraint('sequence >= 1 AND size_bytes >= 0', name='ck_message_attachments_counts'),
    sa.ForeignKeyConstraint(['created_by'], ['notificaciones.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['notificaciones.actors.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['notificaciones.messages.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['notificaciones.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'sequence', name='uq_message_attachments_message_sequence'),
    schema='notificaciones'
    )
    op.create_table('message_attempts',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('smtp_account_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('smtp_code', sa.Integer(), nullable=True),
    sa.Column('error_kind', sa.String(length=100), nullable=True),
    sa.Column('smtp_response', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("outcome IN ('sent', 'transient_error', 'permanent_error', 'uncertain', 'no_account')", name='ck_message_attempts_outcome'),
    sa.CheckConstraint('attempt_number >= 1', name='ck_message_attempts_number'),
    sa.ForeignKeyConstraint(['created_by'], ['notificaciones.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['notificaciones.actors.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['notificaciones.messages.id'], ),
    sa.ForeignKeyConstraint(['smtp_account_id'], ['notificaciones.smtp_accounts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['notificaciones.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='notificaciones'
    )
    op.create_index('ix_message_attempts_message_number', 'message_attempts', ['message_id', 'attempt_number'], unique=False, schema='notificaciones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )