"""cuentas smtp

Revision ID: f8f8c64376a3
Revises: 55354ede02b0
Create Date: 2026-10-01 05:41:37.082581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f8c64376a3'
down_revision: Union[str, Sequence[str], None] = '55354ede02b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta revisión."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smtp_accounts',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('security', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('from_name', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("security IN ('starttls', 'ssl')", name='ck_smtp_accounts_security'),
    sa.CheckConstraint('port BETWEEN 1 AND 65535', name='ck_smtp_accounts_port'),
    sa.CheckConstraint('priority >= 0', name='ck_smtp_accounts_priority'),
    sa.CheckConstraint('timeout_seconds BETWEEN 1 AND 120', name='ck_smtp_accounts_timeout'),
    sa.ForeignKeyConstraint(['created_by'], ['notificaciones.actors.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['notificaciones.actors.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['notificaciones.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='notificaciones'
    )
    op.create_index('ix_smtp_accounts_company_active_priority', 'smtp_accounts', ['company_id', 'is_active', 'priority'], unique=False, schema='notificaciones')
    op.create_index('uq_smtp_accounts_company_name_active', 'smtp_accounts', ['company_id', 'name'], unique=True, schema='notificaciones', postgresql_where=sa.text('is_active'), mssql_where=sa.text('is_active = 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Los retrocesos destructivos requieren una decisión explícita."""
    raise RuntimeError(
        "Downgrade deshabilitado; preparar una migración correctiva."
    )